import { Command } from 'commander';
import { loadConfigFromEnv, validateConfig } from '@nomik/core';
import { createGraphService } from '@nomik/graph';
import { readProjectConfig } from '../utils/project-config.js';
import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

export const wikiCommand = new Command('wiki')
    .description('Generate markdown documentation from the knowledge graph')
    .option('--out <dir>', 'Output directory', './wiki')
    .option('--json', 'Output as JSON instead of markdown files')
    .action(async (opts: { out: string; json?: boolean }) => {
        const envConfig = loadConfigFromEnv();
        const config = validateConfig({
            ...envConfig,
            target: { root: '.' },
        });

        const graph = createGraphService(config.graph);

        try {
            await graph.connect();

            const projectConfig = readProjectConfig();
            const projectId = projectConfig?.projectId;
            const projectName = projectConfig?.projectName ?? 'unknown';

            // Gather data
            const stats = await graph.getStats(projectId);
            const deadCode = await graph.getDeadCode(projectId);
            const godFiles = await graph.getGodFiles(10, projectId);
            const duplicates = await graph.getDuplicates(projectId);
            const serviceLinks = await graph.getServiceLinks(projectId);

            // Get file-level data
            const files = await graph.executeQuery<{
                path: string; language: string; functionCount: number; lineCount: number;
            }>(
                `MATCH (f:File)${projectId ? ' WHERE f.projectId = $projectId' : ''}
                 OPTIONAL MATCH (f)-[:CONTAINS]->(fn:Function)
                 WITH f, count(fn) as functionCount
                 RETURN f.path as path, COALESCE(f.language, 'unknown') as language,
                        functionCount, COALESCE(f.lineCount, 0) as lineCount
                 ORDER BY f.path`,
                { projectId },
            );

            // Get top-level functions with caller counts
            const functions = await graph.executeQuery<{
                name: string; filePath: string; isExported: boolean; callerCount: number; calleeCount: number;
            }>(
                `MATCH (fn:Function)${projectId ? ' WHERE fn.projectId = $projectId' : ''}
                 OPTIONAL MATCH (caller)-[:CALLS]->(fn)
                 WITH fn, count(DISTINCT caller) as callerCount
                 OPTIONAL MATCH (fn)-[:CALLS]->(callee)
                 RETURN fn.name as name, fn.filePath as filePath,
                        COALESCE(fn.isExported, false) as isExported,
                        callerCount, count(DISTINCT callee) as calleeCount
                 ORDER BY callerCount DESC
                 LIMIT 100`,
                { projectId },
            );

            if (opts.json) {
                console.log(JSON.stringify({ project: projectName, stats, files, functions, deadCode, godFiles, duplicates, serviceLinks }, null, 2));
                return;
            }

            // Generate markdown files
            mkdirSync(opts.out, { recursive: true });
            const now = new Date().toISOString().split('T')[0];

            // 1. Index page
            let index = `# ${projectName} — Architecture Wiki\n\n`;
            index += `> Auto-generated by NOMIK on ${now}\n\n`;
            index += `## Overview\n\n`;
            index += `| Metric | Count |\n|---|---|\n`;
            index += `| Files | ${stats.fileCount} |\n`;
            index += `| Functions | ${stats.functionCount} |\n`;
            index += `| Classes | ${stats.classCount} |\n`;
            index += `| Routes | ${stats.routeCount} |\n`;
            index += `| Dead code | ${deadCode.length} |\n`;
            index += `| God files | ${godFiles.length} |\n`;
            index += `| Duplicates | ${duplicates.length} |\n\n`;

            index += `## Files\n\n`;
            index += `| File | Language | Functions | Lines |\n|---|---|---|---|\n`;
            for (const f of files) {
                const shortPath = f.path.split(/[/\\]/).slice(-3).join('/');
                index += `| ${shortPath} | ${f.language} | ${f.functionCount} | ${f.lineCount} |\n`;
            }
            index += `\n`;

            writeFileSync(join(opts.out, 'index.md'), index);
            console.log(`  📄 ${join(opts.out, 'index.md')}`);

            // 2. Functions page
            let funcsPage = `# Functions\n\n`;
            funcsPage += `> Top 100 functions by caller count\n\n`;
            funcsPage += `| Function | File | Exported | Callers | Callees |\n|---|---|---|---|---|\n`;
            for (const fn of functions) {
                const shortPath = fn.filePath.split(/[/\\]/).slice(-2).join('/');
                funcsPage += `| ${fn.name} | ${shortPath} | ${fn.isExported ? 'yes' : 'no'} | ${fn.callerCount} | ${fn.calleeCount} |\n`;
            }
            funcsPage += `\n`;

            writeFileSync(join(opts.out, 'functions.md'), funcsPage);
            console.log(`  📄 ${join(opts.out, 'functions.md')}`);

            // 3. Health page
            let healthPage = `# Health Report\n\n`;

            if (deadCode.length > 0) {
                healthPage += `## Dead Code (${deadCode.length})\n\n`;
                healthPage += `| Function | File |\n|---|---|\n`;
                for (const d of deadCode) {
                    healthPage += `| ${d.name} | ${d.filePath.split(/[/\\]/).slice(-2).join('/')} |\n`;
                }
                healthPage += `\n`;
            } else {
                healthPage += `## Dead Code\n\n✅ No dead code detected.\n\n`;
            }

            if (godFiles.length > 0) {
                healthPage += `## God Files (${godFiles.length})\n\n`;
                healthPage += `| File | Functions | Lines |\n|---|---|---|\n`;
                for (const g of godFiles) {
                    healthPage += `| ${g.filePath.split(/[/\\]/).slice(-2).join('/')} | ${g.functionCount} | ${g.totalLines} |\n`;
                }
                healthPage += `\n`;
            } else {
                healthPage += `## God Files\n\n✅ No god files detected.\n\n`;
            }

            if (duplicates.length > 0) {
                healthPage += `## Duplicate Functions (${duplicates.length})\n\n`;
                for (const d of duplicates) {
                    healthPage += `### Hash: \`${d.bodyHash.substring(0, 12)}\` (${d.count} copies)\n\n`;
                    for (const f of d.functions) {
                        healthPage += `- \`${f.name}\` in ${f.filePath.split(/[/\\]/).slice(-2).join('/')}\n`;
                    }
                    healthPage += `\n`;
                }
            } else {
                healthPage += `## Duplicate Functions\n\n✅ No duplicates detected.\n\n`;
            }

            writeFileSync(join(opts.out, 'health.md'), healthPage);
            console.log(`  📄 ${join(opts.out, 'health.md')}`);

            // 4. Service links page
            if (serviceLinks.length > 0) {
                let svcPage = `# Cross-Service Links\n\n`;
                for (const link of serviceLinks) {
                    svcPage += `## ${link.topicName} (${link.broker})\n\n`;
                    svcPage += `**Producers:**\n`;
                    for (const p of link.producers) svcPage += `- ${p.name} (${p.filePath.split(/[/\\]/).slice(-2).join('/')})\n`;
                    svcPage += `\n**Consumers:**\n`;
                    for (const c of link.consumers) svcPage += `- ${c.name} (${c.filePath.split(/[/\\]/).slice(-2).join('/')})\n`;
                    svcPage += `\n`;
                }
                writeFileSync(join(opts.out, 'service-links.md'), svcPage);
                console.log(`  📄 ${join(opts.out, 'service-links.md')}`);
            }

            console.log(`\n  ✅ Wiki generated in ${opts.out}/ (${opts.json ? 'JSON' : 'markdown'})\n`);
        } catch (err) {
            console.error(`  ❌ Error: ${err instanceof Error ? err.message : String(err)}\n`);
        } finally {
            await graph.disconnect();
        }
    });
